In [1]:
import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt
import warnings

pd.set_option('display.max_columns', None)
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('files/bank-additional_clean.csv', index_col=0)
df.head(3)

,income,kidhome,teenhome,dt_customer,numwebvisitsmonth,id,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,empvarrate,conspriceidx,consconfidx,euribor3m,nremployed,y,date,latitude,longitude,contact_month,contact_year,age_cat
0,161770,1,0,2012-04-04,29,089b39d8-e4d0-461b-87d4-814d71e0e079,NaN,housemaid,married,basic 4y,No,No,No,telephone,261,1,NaN,0,nonexistent,1.1,93.994,-36.4,4.857,5191,no,2-agosto-2019,41.495,-71.233,agosto,2019.0,Adultos mayores
1,85477,1,1,2012-12-30,7,e9d37224-cb6f-4942-98d7-46672963d097,57.0,services,married,high school,NaN,No,No,telephone,149,1,NaN,0,nonexistent,1.1,93.994,-36.4,NaN,5191,no,14-septiembre-2016,34.601,-83.923,septiembre,2016.0,Mediana edad
2,147233,1,1,2012-02-02,5,3f9f49b5-e410-4948-bf6e-f9244f04918b,37.0,services,married,high school,No,Si,No,telephone,226,1,NaN,0,nonexistent,1.1,93.994,-36.4,4.857,5191,no,15-febrero-2019,34.939,-94.847,febrero,2019.0,Adultos jóvenes

# Outliers: 
- un valor que sale de lo normal.

In [3]:
q1 = df['age'].quantile(0.25)
q3 = df['age'].quantile(0.75)

iqr = q3 - q1

In [7]:
lower = q1 - 1.5*iqr
upper = q3 + 1.5*iqr

In [8]:
outliers = df[(df['age']< lower) | (df['age']> upper)]

In [9]:
outliers

,income,kidhome,teenhome,dt_customer,numwebvisitsmonth,id,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,empvarrate,conspriceidx,consconfidx,euribor3m,nremployed,y,date,latitude,longitude,contact_month,contact_year,age_cat
27569,115345,1,1,2013-04-06,5,57480a2d-886a-49d2-b9e7-1c5ce0e44dea,70.0,retired,divorced,basic 4y,No,Si,No,cellular,187,3,NaN,0,nonexistent,-1.8,92.843,-50.0,1.811,"5099,1",yes,4-marzo-2016,27.445,-120.794,marzo,2016.0,Adultos mayores
27613,91910,0,2,2013-02-21,4,e032249d-dd8c-45de-84f6-f7d596896c0d,76.0,retired,married,university degree,No,No,Si,cellular,167,9,NaN,0,nonexistent,-1.8,92.843,-50.0,NaN,"5099,1",no,13-septiembre-2018,39.467,-120.994,septiembre,2018.0,Adultos mayores
27636,56116,2,2,2013-09-11,6,73f44f0c-2474-4622-85c1-5984ddbcc493,73.0,retired,married,university degree,No,Si,No,cellular,179,1,NaN,1,failure,-1.8,92.843,-50.0,1.687,"5099,1",no,21-julio-2017,40.799,-106.545,julio,2017.0,Adultos mayores
27656,78082,0,0,2013-10-23,3,cadf82d4-4575-4e46-8758-c03c5ad864a7,88.0,retired,divorced,basic 4y,No,Si,No,cellular,48,1,NaN,0,nonexistent,-1.8,92.843,-50.0,1.663,"5099,1",no,26-diciembre-2016,32.681,-108.809,diciembre,2016.0,Adultos mayores
27658,158653,1,1,2013-08-07,4,bec707e8-5906-4288-82dd-1865a34c9b41,88.0,retired,divorced,basic 4y,No,No,No,cellular,266,2,NaN,0,nonexistent,-1.8,92.843,-50.0,1.663,"5099,1",yes,25-febrero-2016,42.104,-72.477,febrero,2016.0,Adultos mayores
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42611,62174,2,2,2014-08-27,2,2972b93b-a8b9-4552-b684-f2c1b0a532f3,70.0,retired,married,basic 4y,No,Si,No,cellular,331,1,3.0,2,success,-1.8,93.876,-40.0,0.683,"5008,7",yes,9-marzo-2018,44.069,-118.819,marzo,2018.0,Adultos mayores
42689,171068,2,2,2014-12-30,9,706d9909-5a23-490c-923a-9ab934acdad4,72.0,retired,divorced,basic 4y,No,Si,Si,cellular,238,2,NaN,1,failure,-2.9,92.201,-31.4,0.873,"5076,2",no,26-junio-2019,32.348,-97.417,junio,2019.0,Adultos mayores
42832,159290,0,1,2014-08-28,22,752c6d29-6ad0-4e12-9e6c-ea01fe1a6b94,72.0,NaN,married,NaN,No,Si,Si,cellular,207,8,NaN,1,failure,-2.9,92.201,-31.4,0.825,"5076,2",yes,4-noviembre-2017,32.704,-111.544,noviembre,2017.0,Adultos mayores
42912,38123,0,2,2014-12-23,8,d797d0e9-356e-4efd-a898-0514bb177cb6,74.0,retired,divorced,basic 4y,No,Si,No,cellular,142,2,NaN,0,nonexistent,-1.8,93.749,-34.6,0.643,"5008,7",yes,2-abril-2016,27.572,-95.418,abril,2016.0,Adultos mayores
42966,43187,1,2,2014-02-28,31,1b4ab7f3-947d-4588-8b30-6ff57d628c5b,73.0,retired,married,basic 4y,No,Si,No,cellular,158,1,6.0,1,success,-1.8,93.075,-47.1,1.405,"5099,1",no,6-junio-2017,43.862,-123.229,junio,2017.0,Adultos mayores