In [1]:
import requests
import pandas as pd
import mysql.connector
from mysql.connector import Error
import numpy as np
import os
from dotenv import load_dotenv

load_dotenv()

False

In [2]:
# fase 1. Extracción de datos de películas navideñas desde un API. 
## Buenas practicas: uso de try/except, uso de funciones , verificar los tipos de respuestas
url = "https://beta.adalab.es/resources/apis/christmas.json"
datos = requests.get(url)
print(datos.status_code)
print(datos.content)

datos_pelis = datos.json()
print(datos_pelis)

200

In [3]:
datos_pelis

[{'title': 'Love Actually',
  'rating': 'R',
  'runtime': 135.0,
  'imdb_rating': 7.6,
  'meta_score': 55.0,
  'genre': 'Comedy, Drama, Romance',
  'release_year': 2003.0,
  'description': 'Follows the lives of eight very different couples in dealing with their love lives in various loosely interrelated tales all set during a frantic month before Christmas in London, England.',
  'director': 'Richard Curtis',
  'stars': 'Hugh Grant, Martine McCutcheon, Liam Neeson, Laura Linney, ',
  'votes': '517,283',
  'gross': '$59.70M',
  'img_src': 'https://m.media-amazon.com/images/M/MV5BNThkNjgxNGQtOTIxMy00ZTFmLWIwMDItYzE5YzM3ZDMzNDE3XkEyXkFqcGdeQXVyMTUyNjc3NDQ4._V1_UY209_CR3,0,140,209_AL_.jpg',
  'type': 'Movie'},
 {'title': 'Home Alone',
  'rating': 'PG',
  'runtime': 103.0,
  'imdb_rating': 7.7,
  'meta_score': 63.0,
  'genre': 'Comedy, Family',
  'release_year': 1990.0,
  'description': 'An eight-year-old troublemaker, mistakenly left home alone, must defend his home against a pair of burglars on Christmas Eve.',
  'director': 'Chris Columbus',
  'stars': 'Macaulay Culkin, Joe Pesci, Daniel Stern, John Heard, ',
  'votes': '629,713',
  'gross': '$285.76M',
  'img_src': 'https://m.media-amazon.com/images/M/MV5BMzFkM2YwOTQtYzk2Mi00N2VlLWE3NTItN2YwNDg1YmY0ZDNmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UY209_CR0,0,140,209_AL_.jpg',
  'type': 'Movie'},
 {'title': "National Lampoon's Christmas Vacation",
  'rating': 'PG-13',
  'runtime': 97.0,
  'imdb_rating': 7.5,
  'meta_score': 49.0,
  'genre': 'Comedy',
  'release_year': 1989.0,
  'description': "The Griswold family's plans for a big family Christmas predictably turn into a big disaster.",
  'director': 'Jeremiah S. Chechik',
  'stars': "Chevy Chase, Beverly D'Angelo, Juliette Lewis, Johnny Galecki, ",
  'votes': '213,196',
  'gross': '$71.32M',
  'img_src': 'https://m.media-amazon.com/images/M/MV5BMGZkMWQ2MzMtYTkxYS00OThmLWI0ZTQtNmY0ZTkyY2E4MjliXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UY209_CR0,0,140,209_AL_.jpg',
  'type': 'Movie'},
 {'title': 'Elf',
  'rating': 'PG',
  'runtime': 97.0,
  'imdb_rating': 7.1,
  'meta_score': 66.0,
  'genre': 'Adventure, Comedy, Family',
  'release_year': 2003.0,
  'description': "Raised as an oversized elf, Buddy travels from the North Pole to New York City to meet his biological father, Walter Hobbs, who doesn't know he exists and is in desperate need of some Christmas spirit.",
  'director': 'Jon Favreau',
  'stars': 'Will Ferrell, James Caan, Bob Newhart, Zooey Deschanel, ',
  'votes': '300,546',
  'gross': '$173.40M',
  'img_src': 'https://m.media-amazon.com/images/M/MV5BMzUxNzkzMzQtYjIxZC00NzU0LThkYTQtZjNhNTljMTA1MDA1L2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UY209_CR0,0,140,209_AL_.jpg',
  'type': 'Movie'},
 {'title': 'How the Grinch Stole Christmas',
  'rating': 'PG',
  'runtime': 104.0,
  'imdb_rating': 6.3,
  'meta_score': 46.0,
  'genre': 'Comedy, Family, Fantasy',
  'release_year': 2000.0,
  'description': 'On the outskirts of Whoville lives a green, revenge-seeking Grinch who plans to ruin Christmas for all of the citizens of the town.',
  'director': 'Ron Howard',
  'stars': 'Jim Carrey, Taylor Momsen, Kelley, Jeffrey Tambor, ',
  'votes': '280,898',
  'gross': '$260.04M',
  'img_src': 'https://m.media-amazon.com/images/M/MV5BNWNiNTczNzEtMjQyZC00MjFmLTkzMDMtODk4ZGMyZmE0N2E4XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UY209_CR0,0,140,209_AL_.jpg',
  'type': 'Movie'},
 {'title': 'The Grinch',
  'rating': 'PG',
  'runtime': 85.0,
  'imdb_rating': 6.4,
  'meta_score': 51.0,
  'genre': 'Animation, Comedy, Family',
  'release_year': 2018.0,
  'description': 'A grumpy Grinch plots to ruin Christmas for the village of Whoville.',
  'director': 'Yarrow Cheney',
  'stars': 'Scott Mosier, Benedict Cumberbatch, Cameron Seely, Rashida Jones, Pharrell Williams, ',
  'votes': '85,219',
  'gross': '$270.62M',
  'img_src': 'https://m.media-amazon.com/images/M/MV5BYmE5Yjg0MzktYzgzMi00YTFiLWJjYTItY2M5MmI1ODI4MDY3XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UX140_CR0,0,140,209_AL_.jpg',
  'type': 'Movie'},
 {'title': 'Die Hard',
  'rating': 'R',
  'runtime': 132.0,
  'imdb_rating': 8.2,
  'meta_score': 72.0,
  'genre': 'Action, Thriller',
  'release_year': 1988.0,
  'description': 'A New York City police officer tries to save his estranged wife and several others taken hostage by terrorists during a Christmas party at the Nakatomi Plaza in Los Angeles.',
  'director': 'John McTiernan',
  'stars': 'Bruce Willis, Alan Rickman, Bonnie Bedelia, Reginald VelJohnson, ',
  'votes': '924,658',
  'gross': '$83.01M',
  'img_src': 'https://m.media-amazon.com/images/M/MV5BZjRlNDUxZjAtOGQ4OC00OTNlLTgxNmQtYTBmMDgwZmNmNjkxXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX140_CR0,0,140,209_AL_.jpg',
  'type': 'Movie'},
 {'title': 'Home Alone 2: Lost in New York',
  'rating': 'PG',
  'runtime': 120.0,
  'imdb_rating': 6.9,
  'meta_score': 46.0,
  'genre': 'Adventure, Comedy, Crime',
  'release_year': 1992.0,
  'description': 'One year after Kevin McCallister was left home alone and had to defeat a pair of bumbling burglars, he accidentally finds himself stranded in New York City - and the same criminals are not far behind.',
  'director': 'Chris Columbus',
  'stars': "Macaulay Culkin, Joe Pesci, Daniel Stern, Catherine O'Hara, ",
  'votes': '389,541',
  'gross': '$173.59M',
  'img_src': 'https://m.media-amazon.com/images/M/MV5BNDI1MzM0Y2YtYmIyMS00ODE3LTlhZjEtZTUyNmEzMTNhZWU5XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UY209_CR0,0,140,209_AL_.jpg',
  'type': 'Movie'},
 {'title': 'The Polar Express',
  'rating': 'G',
  'runtime': 100.0,
  'imdb_rating': 6.6,
  'meta_score': 61.0,
  'genre': 'Animation, Adventure, Comedy',
  'release_year': 2004.0,
  'description': 'On Christmas Eve, a young boy embarks on a magical adventure to the North Pole on the Polar Express, while learning about friendship, bravery, and the spirit of Christmas.',
  'director': 'Robert Zemeckis',
  'stars': 'Tom Hanks, Chris Coppola, Michael Jeter, Leslie Zemeckis, ',
  'votes': '233,258',
  'gross': '$183.37M',
  'img_src': 'https://m.media-amazon.com/images/M/MV5BMTM1NTU0NTE4MV5BMl5BanBnXkFtZTcwMTQ0MjEzMw@@._V1_UY209_CR0,0,140,209_AL_.jpg',
  'type': 'Movie'},
 {'title': "It's a Wonderful Life",
  'rating': 'PG',
  'runtime': 130.0,
  'imdb_rating': 8.6,
  'meta_score': 89.0,
  'genre': 'Drama, Family, Fantasy',
  'release_year': 1946.0,
  'description': 'An angel is sent from Heaven to help a desperately frustrated businessman by showing him what life would have been like if he had never existed.',
  'director': 'Frank Capra',
  'stars': 'James Stewart, Donna Reed, Lionel Barrymore, Thomas Mitchell, ',
  'votes': '486,479',
  'gross': None,
  'img_src': 'https://m.media-amazon.com/images/M/MV5BZjc4NDZhZWMtNGEzYS00ZWU2LThlM2ItNTA0YzQ0OTExMTE2XkEyXkFqcGdeQXVyNjUwMzI2NzU@._V1_UY209_CR2,0,140,209_AL_.jpg',
  'type': 'Movie'},
 {'title': 'The Santa Clause',
  'rating': 'PG',
  'runtime': 97.0,
  'imdb_rating': 6.6,
  'meta_score': 57.0,
  'genre': 'Comedy, Drama, Family',
  'release_year': 1994.0,
  'description': 'When a man inadvertently makes Santa fall off his roof on Christmas Eve, he finds himself magically recruited to take his place.',
  'director': 'John Pasquin',
  'stars': 'Tim Allen, Judge Reinhold, Wendy Crewson, Eric Lloyd, ',
  'votes': '130,393',
  'gross': '$144.83M',
  'img_src': 'https://m.media-amazon.com/images/M/MV5BMTZlNzk1MjItYjJlYy00MTAxLWJkNjEtZmNiNmVlNjQ4NDE5XkEyXkFqcGdeQXVyMzI0NDc4ODY@._V1_UX140_CR0,0,140,209_AL_.jpg',
  'type': 'Movie'},
 {'title': 'White Christmas',
  'rating': 'Not Rated',
  'runtime': 120.0,
  'imdb_rating': 7.6,
  'meta_score': 56.0,
  'genre': 'Comedy, Musical, Romance',
  'release_year': 1954.0,
  'description': 'A successful song-and-dance team become romantically involved with a sister act and team up to save the failing Vermont inn of their former commanding general.',
  'director': 'Michael Curtiz',
  'stars': 'Bing Crosby, Danny Kaye, Rosemary Clooney, Vera-Ellen, ',
  'votes': '48,751',
  'gross': '$30.00M',
  'img_src': 'https://m.media-amazon.com/images/M/MV5BYjI0ZTk0ZjQtZTMzOS00NDdmLTk0YzUtZTQ4NGRkNWFhZTkxXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_UX140_CR0,0,140,209_AL_.jpg',
  'type': 'Movie'},
 {'title': 'Scrooged',
  'rating': 'PG-13',
  'runtime': 101.0,
  'imdb_rating': 6.9,
  'meta_score': 38.0,
  'genre': 'Comedy, Drama, Fantasy',
  'release_year': 1988.0,
  'description': 'A selfish, cynical television executive is haunted by three spirits bearing lessons on Christmas Eve.',
  'director': 'Richard Donner',
  'stars': 'Bill Murray, Karen Allen, John Forsythe, John Glover, ',
  'votes': '112,793',
  'gross': '$60.33M',
  'img_src': 'https://m.media-amazon.com/images/M/MV5BZDExMjFhYTItNmFkNC00YzQ0LWE1OGMtN2ExNGFkNWMxMjA4XkEyXkFqcGdeQXVyNjc5NjEzNA@@._V1_UX140_CR0,0,140,209_AL_.jpg',
  'type': 'Movie'},
 {'title': 'Spirited',
  'rating': 'PG-13',
  'runtime': 127.0,
  'imdb_rating': 6.6,
  'meta_score': 55.0,
  'genre': 'Comedy, Family, Musical',
  'release_year': 2022.0,
  'description': "A musical version of Charles Dickens's story of a miserly misanthrope who is taken on a magical journey.",
  'director': 'Sean Anders',
  'stars': 'Will Ferrell, Ryan Reynolds, Octavia Spencer, Patrick Page, ',
  'votes': '46,695',
  'gross': None,
  'img_src': 'https://m.media-amazon.com/images/M/MV5BY2RlZGFmYjAtNGZiMi00YjQ5LWE0ZmQtZmIyM2VmMjRhMTJlXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_UY209_CR0,0,140,209_AL_.jpg',
  'type': 'Movie'},
 {'title': 'Miracle on 34th Street',
  'rating': 'PG',
  'runtime': 114.0,
  'imdb_rating': 6.6,
  'meta_score': None,
  'genre': 'Drama, Family, Fantasy',
  'release_year': 1994.0,
  'description': 'A lawyer and a little girl must prove that a man claiming to be Santa Claus is the real thing.',
  'director': 'Les Mayfield',
  'stars': 'Richard Attenborough, Elizabeth Perkins, Dylan McDermott, J.T. Walsh, ',
  'votes': '42,222',
  'gross': '$17.19M',
  'img_src': 'https://m.media-amazon.com/images/M/MV5BZjk3M2UyN2YtNmQ1MS00MWI3LWEzNGMtYTRkM2E5MWNjOWJjL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UY209_CR0,0,140,209_AL_.jpg',
  'type': 'Movie'},
 {'title': 'Jingle All the Way',
  'rating': 'PG',
  'runtime': 89.0,
  'imdb_rating': 5.7,
  'meta_score': 34.0,
  'genre': 'Adventure, Comedy, Family',
  'release_year': 1996.0,
  'description': 'A father vows to get his son a Turbo Man action figure for Christmas. However, every store is sold out, and he must travel all over town and compete with everybody else in order to find one.',
  'director': 'Brian Levant',
  'stars': 'Arnold Schwarzenegger, Sinbad, Phil Hartman, Rita Wilson, ',
  'votes': '113,346',
  'gross': '$60.57M',
  'img_src': 'https://m.media-amazon.com/images/M/MV5BMmJlYzViNzctMjQ1Ni00ZWQ4LThkN2YtMzI2ZGU5Nzk0NTAyXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX140_CR0,0,140,209_AL_.jpg',
  'type': 'Movie'},
 {'title': 'Klaus',
  'rating': 'PG',
  'runtime': 96.0,
  'imdb_rating': 8.2,
  'meta_score': 65.0,
  'genre': 'Animation, Adventure, Comedy',
  'release_year': 2019.0,
  'description': "A simple act of kindness always sparks another, even in a frozen, faraway place. When Smeerensburg's new postman, Jesper, befriends toymaker Klaus, their gifts melt an age-old feud and deliver a sleigh full of holiday traditions.",
  'director': 'Sergio Pablos',
  'stars': 'Carlos Martínez López, Jason Schwartzman, J.K. Simmons, Rashida Jones, Will Sasso, ',
  'votes': '178,753',
  'gross': None,
  'img_src': 'https://m.media-amazon.com/images/M/MV5BMWYwOThjM2ItZGYxNy00NTQwLWFlZWEtM2MzM2Q5MmY3NDU5XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UY209_CR0,0,140,209_AL_.jpg',
  'type': 'Movie'},
 {'title': 'A Christmas Carol',
  'rating': 'PG',
  'runtime': 96.0,
  'imdb_rating': 6.8,
  'meta_score': 55.0,
  'genre': 'Animation, Adventure, Comedy',
  'release_year': 2009.0,
  'description': "An animated retelling of Charles Dickens' classic novel about a Victorian-era miser taken on a journey of self-redemption, courtesy of several mysterious Christmas apparitions.",
  'director': 'Robert Zemeckis',
  'stars': 'Jim Carrey, Gary Oldman, Colin Firth, Steve Valentine, ',
  'votes': '126,638',
  'gross': '$137.86M',
  'img_src': 'https://m.media-amazon.com/images/M/MV5BMTM1MTI5ODU4MV5BMl5BanBnXkFtZTcwNTYyNTU4Mg@@._V1_UY209_CR0,0,140,209_AL_.jpg',
  'type': 'Movie'},
 {'title': 'Last Christmas',
  'rating': 'PG-13',
  'runtime': 103.0,
  'imdb_rating': 6.5,
  'meta_score': 50.0,
  'genre': 'Comedy, Drama, Fantasy',
  'release_year': 2019.0,
  'description': 'Kate is a young woman subscribed to bad decisions. Working as an elf in a year-round Christmas store is not good for the wannabe singer. However, she meets Tom there. Her life takes a new turn--that seems too good to be true.',
  'director': 'Paul Feig',
  'stars': 'Madison Ingoldsby, Emma Thompson, Boris Isakovic, Lucy Miller, ',
  'votes': '87,409',
  'gross': '$35.15M',
  'img_src': 'https://m.media-amazon.com/images/M/MV5BNTQ4ZmY0NjgtYzVhNy00NzhiLTk3YTYtNzM1MTdjM2VhZDA3XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UY209_CR0,0,140,209_AL_.jpg',
  'type': 'Movie'},
 {'title': 'Christmas with the Kranks',
  'rating': 'PG',
  'runtime': 99.0,
  'imdb_rating': 5.5,
  'meta_score': 22.0,
  'genre': 'Comedy, Family',
  'release_year': 2004.0,
  'description': 'With their daughter, Blair, away in Peru, Luther and Nora Krank decide to skip Christmas all together until she decides to come home, causing an uproar when they have to celebrate it at the last minute.',
  'director': 'Joe Roth',
  'stars': 'Tim Allen, Jamie Lee Curtis, Dan Aykroyd, M. Emmet Walsh, ',
  'votes': '55,959',
  'gross': '$73.78M',
  'img_src': 'https://m.media-amazon.com/images/M/MV5BMTQxMDMxODEwNF5BMl5BanBnXkFtZTYwNzM4OTc2._V1_UY209_CR0,0,140,209_AL_.jpg',
  'type': 'Movie'},
 {'title': 'The Santa Clause 2',
  'rating': 'G',
  'runtime': 104.0,
  'imdb_rating': 5.7,
  'meta_score': 48.0,
  'genre': 'Comedy, Family, Fantasy',
  'release_year': 2002.0,
  'description': "Scott Calvin has been a humble Santa Claus for eight years, but it might come to an end if he doesn't find a Mrs. Claus.",
  'director': 'Michael Lembeck',
  'stars': 'Tim Allen, Spencer Breslin, Elizabeth Mitchell, Eric Lloyd, ',
  'votes': '62,886',
  'gross': '$139.24M',
  'img_src': 'https://m.media-amazon.com/images/M/MV5BNjU0Njk5MTA2Nl5BMl5BanBnXkFtZTYwODkzMzQ3._V1_UY209_CR0,0,140,209_AL_.jpg',
  'type': 'Movie'},
 {'title': 'Miracle on 34th Street',
  'rating': 'Not Rated',
  'runtime': 96.0,
  'imdb_rating': 7.9,
  'meta_score': 88.0,
  'genre': 'Comedy, Drama, Family',
  'release_year': 1947.0,
  'description': "After a divorced New York mother hires a nice old man to play Santa Claus at Macy's, she is startled by his claim to be the genuine article. When his sanity is questioned, a lawyer defends him in court by arguing that he's not mistaken.",
  'director': 'George Seaton',
  'stars': "Edmund Gwenn, Maureen O'Hara, John Payne, Gene Lockhart, ",
  'votes': '53,189',
  'gross': '$2.65M',
  'img_src': 'https://m.media-amazon.com/images/M/MV5BNjRkOGEwYTUtY2E5Yy00ODg4LTk2ZWItY2IyMzUxOGVhMTM1XkEyXkFqcGdeQXVyNDk0MDg4NDk@._V1_UX140_CR0,0,140,209_AL_.jpg',
  'type': 'Movie'},
 {'title': 'Four Christmases',
  'rating': 'PG-13',
  'runtime': 88.0,
  'imdb_rating': 5.7,
  'meta_score': 41.0,
  'genre': 'Comedy, Drama, Romance',
  'release_year': 2008.0,
  'description': 'A couple struggles to visit all four of their divorced parents on Christmas.',
  'director': 'Seth Gordon',
  'stars': 'Reese Witherspoon, Vince Vaughn, Mary Steenburgen, Robert Duvall, ',
  'votes': '78,898',
  'gross': '$120.15M',
  'img_src': 'https://m.media-amazon.com/images/M/MV5BMTQ2MjA0NDAwNF5BMl5BanBnXkFtZTcwOTU4MTM5MQ@@._V1_UY209_CR0,0,140,209_AL_.jpg',
  'type': 'Movie'},
 {'title': 'Home Alone 3',
  'rating': 'PG',
  'runtime': 102.0,
  'imdb_rating': 4.6,
  'meta_score': None,
  'genre': 'Action, Comedy, Crime',
  'release_year': 1997.0,
  'description': 'Alex Pruitt, an 8-year-old boy living in Chicago, must fend off international spies who seek a top-secret computer chip in his toy car.',
  'director': 'Raja Gosnell',
  'stars': 'Alex D. Linz, Olek Krupa, Rya Kihlstedt, Lenny von Dohlen, ',
  'votes': '124,554',
  'gross': '$30.88M',
  'img_src': 'https://m.media-amazon.com/images/M/MV5BZTJhYjVhOWMtYTUyOS00NWM0LThjNzYtZWYxOTkwN2FhODg2XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX140_CR0,0,140,209_AL_.jpg',
  'type': 'Movie'},
 {'title': 'The Muppet Christmas Carol',
  'rating': 'G',
  'runtime': 85.0,
  'imdb_rating': 7.8,
  'meta_score': 64.0,
  'genre': 'Comedy, Drama, Family',
  'release_year': 1992.0,
  'description': "The Muppets present their own touching rendition of Charles Dickens' classic tale.",
  'director': 'Brian Henson',
  'stars': 'Michael Caine, Dave Goelz, Steve Whitmire, Jerry Nelson, ',
  'votes': '67,536',
  'gross': '$27.28M',
  'img_src': 'https://m.media-amazon.com/images/M/MV5BN2Y0NWRkNWItZWEwNi00MDNlLWJmZDYtNTkwYzI5Nzg4MjVjXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UY209_CR0,0,140,209_AL_.jpg',
  'type': 'Movie'},
 {'title': 'Office Christmas Party',
  'rating': 'R',
  'runtime': 105.0,
  'imdb_rating': 5.9,
  'meta_score': 42.0,
  'genre': 'Comedy',
  'release_year': 2016.0,
  'description': 'When his uptight CEO sister threatens to shut down his branch, the branch manager throws an epic Christmas party in order to land a big client and save the day, but the party gets way out of hand...',
  'director': 'Josh Gordon',
  'stars': 'Will Speck, Jason Bateman, Olivia Munn, T.J. Miller, Jennifer Aniston, ',
  'votes': '86,267',
  'gross': '$54.77M',
  'img_src': 'https://m.media-amazon.com/images/M/MV5BYzgyZjE1MjUtYjFjZS00NzMzLWFmNWMtMDJjNGY0ZTgwYjc3XkEyXkFqcGdeQXVyMjQwMjk0NjI@._V1_UY209_CR2,0,140,209_AL_.jpg',
  'type': 'Movie'},
 {'title': 'Feast of the Seven Fishes',
  'rating': None,
  'runtime': 99.0,
  'imdb_rating': 6.8,
  'meta_score': 68.0,
  'genre': 'Comedy',
  'release_year': 2019.0,
  'description': 'A slice of life story that follows a large Italian family on Christmas Eve as they prepare for the traditional Feast of the Seven Fishes, reminisce about the past, and seek love in the future.',
  'director': 'Robert Tinnell',
  'stars': 'Tony Bingham, Skyler Gisondo, Paul Ben-Victor, Jean Zarzour, ',
  'votes': '2,884',
  'gross': None,
  'img_src': 'https://m.media-amazon.com/images/M/MV5BY2ZiYTA3OGMtMjBkOS00MDczLTkzODUtNDA0NGY1ZGM3M2JjXkEyXkFqcGdeQXVyNDExMzMxNjE@._V1_UX140_CR0,0,140,209_AL_.jpg',
  'type': 'Movie'},
 {'title': 'Bad Santa',
  'rating': 'R',
  'runtime': 92.0,
  'imdb_rating': 7.1,
  'meta_score': 70.0,
  'genre': 'Comedy, Crime, Drama',
  'release_year': 2003.0,
  'description': 'A miserable conman and his partner pose as Santa and his Little Helper to rob department stores on Christmas Eve. But they run into problems when the conman befriends a troubled kid.',
  'director': 'Terry Zwigoff',
  'stars': 'Billy Bob Thornton, Bernie Mac, Lauren Graham, John Ritter, ',
  'votes': '152,299',
  'gross': '$60.06M',
  'img_src': 'https://m.media-amazon.com/images/M/MV5BMjA4Njg1MDcwN15BMl5BanBnXkFtZTYwMzAxNjM3._V1_UY209_CR0,0,140,209_AL_.jpg',
  'type': 'Movie'},
 {'title': 'The Christmas Chronicles',
  'rating': 'PG',
  'runtime': 104.0,
  'imdb_rating': 7.0,
  'meta_score': 52.0,
  'genre': 'Adventure, Comedy, Family',
  'release_year': 2018.0,
  'description': 'The story of sister and brother, Kate and Teddy Pierce, whose Christmas Eve plan to catch Santa Claus on camera turns into an unexpected journey that most kids could only dream about.',
  'director': 'Clay Kaytis',
  'stars': 'Kurt Russell, Darby Camp, Judah Lewis, Oliver Hudson, ',
  'votes': '81,195',
  'gross': None,
  'img_src': 'https://m.media-amazon.com/images/M/MV5BNTA3NjU3OTM2MV5BMl5BanBnXkFtZTgwNjQ2MzE1NjM@._V1_UY209_CR0,0,140,209_AL_.jpg',
  'type': 'Movie'},
 {'title': 'The Nightmare Before Christmas',
  'rating': 'PG',
  'runtime': 76.0,
  'imdb_rating': 7.9,
  'meta_score': 82.0,
  'genre': 'Animation, Family, Fantasy',
  'release_year': 1993.0,

In [4]:
df_christmas = pd.DataFrame(datos_pelis)
df_christmas

,title,rating,runtime,imdb_rating,meta_score,genre,release_year,description,director,stars,votes,gross,img_src,type
0,Love Actually,R,135.0,7.6,55.0,"Comedy, Drama, Romance",2003.0,Follows the lives of eight very different coup...,Richard Curtis,"Hugh Grant, Martine McCutcheon, Liam Neeson, L...","517,283",$59.70M,https://m.media-amazon.com/images/M/MV5BNThkNj...,Movie
1,Home Alone,PG,103.0,7.7,63.0,"Comedy, Family",1990.0,"An eight-year-old troublemaker, mistakenly lef...",Chris Columbus,"Macaulay Culkin, Joe Pesci, Daniel Stern, John...","629,713",$285.76M,https://m.media-amazon.com/images/M/MV5BMzFkM2...,Movie
2,National Lampoon's Christmas Vacation,PG-13,97.0,7.5,49.0,Comedy,1989.0,The Griswold family's plans for a big family C...,Jeremiah S. Chechik,"Chevy Chase, Beverly D'Angelo, Juliette Lewis,...","213,196",$71.32M,https://m.media-amazon.com/images/M/MV5BMGZkMW...,Movie
3,Elf,PG,97.0,7.1,66.0,"Adventure, Comedy, Family",2003.0,"Raised as an oversized elf, Buddy travels from...",Jon Favreau,"Will Ferrell, James Caan, Bob Newhart, Zooey D...","300,546",$173.40M,https://m.media-amazon.com/images/M/MV5BMzUxNz...,Movie
4,How the Grinch Stole Christmas,PG,104.0,6.3,46.0,"Comedy, Family, Fantasy",2000.0,"On the outskirts of Whoville lives a green, re...",Ron Howard,"Jim Carrey, Taylor Momsen, Kelley, Jeffrey Tam...","280,898",$260.04M,https://m.media-amazon.com/images/M/MV5BNWNiNT...,Movie
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
868,CBS News Sunday Morning with Jane Pauley: Epis...,TV-G,NaN,NaN,NaN,"News, Talk-Show",1979.0,The popularity of pickup trucks; Luke Burbank ...,Kate D'Arcy-Coleman,"Jane Pauley, Serena Altschul, Nicholas Britell...",None,None,https://m.media-amazon.com/images/M/MV5BMWJhYz...,TV Episode
869,Honest Ads: If Holiday Movies Were Honest,None,NaN,NaN,NaN,"Short, Comedy",2012.0,What if Hollywood were honest about how they m...,Michael Strauss,"Jack Hunter, Britt Migs, Michael Strauss,",None,None,https://m.media-amazon.com/images/M/MV5BNzY1Nj...,TV Episode
870,Cosmic Cowboys: Céréal Christmas,None,NaN,NaN,NaN,Animation,2004.0,Add a Plot,None,None,None,None,https://m.media-amazon.com/images/S/sash/i-t32...,TV Episode
871,Proper Manors: Christmas Special: Christmas Pa...,None,20.0,NaN,NaN,"Action, Comedy, Crime",2012.0,Miles Barnes is forced to throw contractually-...,Dallin Boyce,"Brandyn Cross, Peter D'Alessio, Janis Race-Big...",None,None,https://m.media-amazon.com/images/S/sash/i-t32...,TV Episode
872,Sacred Music at Christmas: A Choral Christmas,None,NaN,NaN,NaN,"Documentary, Music",2010.0,Add a Plot,None,None,None,None,https://m.media-amazon.com/images/S/sash/i-t32...,TV Episode

In [5]:
df_christmas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 873 entries, 0 to 872
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         873 non-null    object
 1   rating        660 non-null    object
 2   runtime       832 non-null    float64
 3   imdb_rating   839 non-null    float64
 4   meta_score    100 non-null    float64
 5   genre         872 non-null    object
 6   release_year  862 non-null    float64
 7   description   873 non-null    object
 8   director      868 non-null    object
 9   stars         862 non-null    object
 10  votes         839 non-null    object
 11  gross         79 non-null     object
 12  img_src       873 non-null    object
 13  type          873 non-null    object
dtypes: float64(4), object(10)
memory usage: 95.6+ KB

In [6]:
#fase 2: Creación de la Base de Datos
# 2.1 conectarme a mysql 
#mejoras: contraseñas con dotenv, definir funciones
try:
    cnx = mysql.connector.connect(
        host='127.0.0.1',
        user='root',
        password='',
    )
    print('Conexión exitosa')
except Error as e:
    print('Error al conectar:', e)

Conexión exitosa

In [7]:
# 2.2 Crear la bases de datos
try:
    cursor = cnx.cursor()
    query = "CREATE DATABASE IF NOT EXISTS christmas" 
    cursor.execute(query)
    print("Query exitosa")
except Error as e:
    print(e)

Query exitosa

In [9]:
cursor = cnx.cursor()

In [10]:
## crear la estructura de la bases de datos: tengo que pensar si todo va en la misma tabla
# crear tabla
cursor.execute("USE christmas")

query = '''CREATE TABLE christmas_movies (
    id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    rating VARCHAR(20),
    runtime INT,
    imdb_rating DECIMAL(3,1),
    meta_score INT,
    genre VARCHAR(255),
    release_year INT,
    description TEXT,
    director VARCHAR(255),
    stars TEXT,
    votes VARCHAR(50),
    gross VARCHAR(50),
    img_src VARCHAR(500),
    type VARCHAR(50)
);'''

cursor.execute(query)

In [11]:
df_christmas.isnull().sum()

title             0
rating          213
runtime          41
imdb_rating      34
meta_score      773
genre             1
release_year     11
description       0
director          5
stars            11
votes            34
gross           794
img_src           0
type              0
dtype: int64

In [12]:
# insertar en la bases de datos
query_insert = '''   INSERT INTO christmas_movies (title, rating, runtime, imdb_rating, meta_score, 
                              genre, release_year, description, director, stars, 
                              votes, gross, img_src, type) 
VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)  '''

df_clean = df_christmas.replace({np.nan: None, 'nan': None, 'Nan': None})
datos = df_clean.values.tolist()
cursor.executemany(query_insert, datos)
cnx.commit()
print(f"Se han insertado nuevos {cursor.rowcount} valores")

Se han insertado nuevos 873 valores

In [13]:
## consultas sobre la bases de datos 
query ='''select * 
from christmas_movies
order by imdb_rating desc
limit 10 '''

df_top = pd.read_sql(query, cnx)
df_top

/var/folders/cr/f3dqyy756z9ftxxsrmgtgjjh0000gn/T/ipykernel_1566/3318773673.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_top = pd.read_sql(query, cnx)

,id,title,rating,runtime,imdb_rating,meta_score,genre,release_year,description,director,stars,votes,gross,img_src,type
0,868,It's Always Sunny in Philadelphia: A Very Sunn...,TV-MA,43.0,9.2,NaN,Comedy,2005,Dennis and Dee decide to teach Frank a lesson ...,Fred Savage,"Charlie Day, Glenn Howerton, Rob McElhenney, K...","5,153",None,https://m.media-amazon.com/images/M/MV5BNDI5ZT...,TV Episode
1,865,ABC Stage 67: A Christmas Memory,None,51.0,9.0,NaN,"Comedy, Drama, Musical",1966,Its the last Christmas together in Depression ...,Frank Perry,"Geraldine Page, Donnie Melvin, Lavinia Cassels...",258,None,https://m.media-amazon.com/images/M/MV5BYTcxMD...,TV Episode
2,816,A Kylie Christmas: Live from the Royal Albert ...,None,120.0,8.6,NaN,Music,2015,Add a Plot,Paul Dugdale,"Kylie Minogue, Dannii Minogue, Chrissie Hynde,...",52,None,https://m.media-amazon.com/images/M/MV5BNThkY2...,Movie
3,10,It's a Wonderful Life,PG,130.0,8.6,89.0,"Drama, Family, Fantasy",1946,An angel is sent from Heaven to help a despera...,Frank Capra,"James Stewart, Donna Reed, Lionel Barrymore, T...","486,479",None,https://m.media-amazon.com/images/M/MV5BZjc4ND...,Movie
4,185,Anne of Green Gables,TV-G,199.0,8.5,NaN,"Drama, Family",1985,"An orphan girl, sent to an elderly brother and...",Megan Follows,"Colleen Dewhurst, Richard Farnsworth, Patricia...","22,265",None,https://m.media-amazon.com/images/M/MV5BNjBmYj...,Movie
5,836,Jingle Vingle,None,96.0,8.5,NaN,Family,2022,Presenting India's First Christmas Themed Movi...,Mark Sujay Samuel,"Aashit Chatterjee, Vaishnavi Mahant, Matthew D...",129,None,https://m.media-amazon.com/images/M/MV5BNDJmNm...,Movie
6,791,The Original Christmas Classics,None,NaN,8.4,NaN,"Animation, Family",1965,Includes the original stories of Rudolph the R...,None,None,47,None,https://m.media-amazon.com/images/M/MV5BNjg5ZW...,Movie
7,521,Christmas Eve on Sesame Street,TV-Y,60.0,8.4,NaN,"Comedy, Family, Music",1978,Big Bird worries when Oscar tells him that if ...,Jon Stone,"Jim Henson, Frank Oz, Jerry Nelson, Richard Hu...","1,066",None,https://m.media-amazon.com/images/M/MV5BMzVhNz...,Movie
8,68,A Charlie Brown Christmas,TV-G,25.0,8.3,NaN,"Animation, Comedy, Drama",1965,Depressed at the commercialism he sees around ...,Bill Melendez,"Ann Altieri, Chris Doran, Sally Dryer, Bill Me...","42,695",None,https://m.media-amazon.com/images/M/MV5BMzQ3M2...,Movie
9,133,The Apartment,Approved,125.0,8.3,94.0,"Comedy, Drama, Romance",1960,A Manhattan insurance clerk tries to rise in h...,Billy Wilder,"Jack Lemmon, Shirley MacLaine, Fred MacMurray,...","192,532",$18.60M,https://m.media-amazon.com/images/M/MV5BNzkwOD...,Movie

In [15]:
query ='''select
	floor(release_year/10) * 10 as decada, 
    count(*) as total_pelis, 
    round(avg(imdb_rating), 2) as rating_promedio
from christmas_movies
group by decada
order by decada; '''
df_decadas = pd.read_sql(query, cnx)
df_decadas

/var/folders/cr/f3dqyy756z9ftxxsrmgtgjjh0000gn/T/ipykernel_1566/801346332.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_decadas = pd.read_sql(query, cnx)

    decada  total_pelis  rating_promedio
0      NaN           11             2.50
1   1890.0            1             6.40
2   1920.0            3             7.10
3   1930.0           13             7.25
4   1940.0           24             7.00
5   1950.0           13             7.00
6   1960.0           11             7.84
7   1970.0           11             7.04
8   1980.0           18             7.04
9   1990.0           39             6.30
10  2000.0           73             6.14
11  2010.0          374             5.93
12  2020.0          282             5.97